### ISSUE TITLE
Buttons CSS not working

### ISSUE THREAD

**Issue by Mlinnig** [mediarox/pagespeed#1]
First of all, thanks for your effort in wrtiting down this little application. I just uploaded it onto my Website and its working fine except for one thing:some buttons are just showing up in less than half of its original size. 

Any ideas how to fix it?
Thanks

![image](https://cloud.githubusercontent.com/assets/11391880/6747805/af6ee234-cede-11e4-80c0-bc391e80839e.png)

![image](https://cloud.githubusercontent.com/assets/11391880/6747831/f8987bc8-cede-11e4-8f07-2896e2809684.png)

**Comment by mediarox** [comment]
Hi Mlinnig,

thanks for your report. If you give us either your origin html (without extension manipulation) or a test web address, we will look into. Additional informations, like browser and version will be also helpful.

regards,

steven
