### ISSUE TITLE
Exclude scripts

### ISSUE THREAD

**Issue by danielchicote** [mediarox/pagespeed#3]
Hello, there are scripts like google analytics that is recommended to put in the header. It would be great to have an exclusions administrator in the backend. Its only a suggestion, i cant contribute to the module in other form.

Thanks for your work.

**Comment by henkvalk** [comment]
Yes it would be nice if there is a way to exclude scripts or css. When I visit the webshop, the page is without style for a few seconds. So if there can be a little CSS at the top with most necesairy style lines, it would be great.

**Comment by mediarox** [comment]
@danielchicote, @henkvalk Thanks. I've created a task in our project-management to implement two seperate fields for exclusion. I'll get back as soon as there is an update.

**Comment by mediarox** [comment]
@danielchicote, @henkvalk New version 0.0.0.2 with exclude fields is released.
