### ISSUE TITLE
Exclude script by id

### ISSUE THREAD

**Issue by gaiterjones** [mediarox/pagespeed#5]
Is it possible to exclude a script by it's element id i.e.

<script id="exclude_this" ....

**Comment by csssucks** [comment]
Yes, this is possible. The exclude pattern will test the entire script 
expression. This includes the opening and ending tag itself. The pattern 
therefore may match any attribute inside the opening tag.

Hope this helps...

On 26.08.2015 12:29, gaiterjones wrote:

> Is it possible to exclude a script by it's element id i.e.
> 
> <script id="exclude_this" ....
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mediarox/pagespeed/issues/5.

## 

mediarox UG (haftungsbeschränkt)
Otto-von-Guericke-Str. 56b
39104 Magdeburg

Geschäftsführer: Steven Fritzsche, Tobias Bätz

Registergericht: Amtsgericht Stendal
Registernummer: HRB 19333

Tel: 0391 / 55 96 90 1
Fax: 0391 / 58 27 45 3
Web: www.mediarox.de

**Comment by gaiterjones** [comment]
Yes /exclude_this/ works, thanks.
